version: "3.9"
services:
  app:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/conversation-api-db
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

  mongo:
    image: mongo:latest
    container_name: "mongoDB"
    ports:
      - "27017:27017"

  postgres:
    image: postgres:latest
    container_name: "postgreSQL"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"


  redis:
    image: redis:latest
    container_name: "redis"
    ports:
      - "6379:6379"
